### ISSUE TITLE
Update License?

### ISSUE THREAD

**Issue by chrisjbryant** [ztane/python-Levenshtein#83]
Hiya,

Is there any chance of changing the license of this module to make it less restrictive? Ideally I would suggest the MIT license, but you could also update it to GPL v3.

**Comment by maxbachmann** [comment]
> Ideally I would suggest the MIT license

This is not possible, since the initial version stems from a different author and already used this license. In case you need similar features with a more open license, you can use [RapidFuzz](https://github.com/maxbachmann/RapidFuzz).

> but you could also update it to GPL v3.

python-Levenshtein is already licensed under GPLv2-or-later, so you are free to use it in GPLv3 licensed software.

**Comment by chrisjbryant** [comment]
Ok, thanks! I also came across RapidFuzz yesterday, so will consider moving to that. 
Do you have any idea how it compares to python-Levenshtein in terms of speed by any chance?

**Comment by maxbachmann** [comment]
RapidFuzz is significantly faster especially when:
1) processing long strings
2) processing multiple strings using the `process.*` APIs

See https://github.com/ztane/python-Levenshtein/issues/61 for some performance comparisions.

**Comment by chrisjbryant** [comment]
Excellent, thanks!
